### ISSUE TITLE
Make `UnhandledException` more verbose

### ISSUE THREAD

**Issue by abailly** [barrucadu/dejafu#133]
Currently when a run in `ConcST` fails because some exception is thrown, all one gets is a quite uninformative `UnhandledException` constructor of `Failure` type. Given all `Exception` are also `Show` instances, it should be possible to add a textual description of the failure to the constructor.

**Comment by barrucadu** [comment]
Good idea about adding more information to `UnhandledException`, although I think the better solution is to add a `SomeException` to the constructor (and sacrifice the `NFData` instance).

**Comment by abailly** [comment]
👍
