### ISSUE TITLE
Use a new primitive for MonadFail.fail?

### ISSUE THREAD

**Issue by barrucadu** [barrucadu/dejafu#140]
`MonadFail.fail` is implemented by throwing an exception: https://github.com/barrucadu/dejafu/blob/c6af27fffb4b1282e6d59429088fff39c213ec94/dejafu/Test/DejaFu/Conc/Internal/Common.hs#L58 https://github.com/barrucadu/dejafu/blob/c6af27fffb4b1282e6d59429088fff39c213ec94/dejafu/Test/DejaFu/STM/Internal.hs#L58

Which means that, unlike any other use of `error` or the like, `fail` can be caught!  If there were a new primitive, `AFail`/`SFail` (where a transaction ending with `SFail` would result in the exception being propagated with `AFail`, like the current exception semantics), then the failure could still be displayed in a nice way without crashing dejafu.

**Comment by qrilka** [comment]
@barrucadu what do you think to use as an implementation for that action? Just doing `fail` of "base" monad (which probably will be `IO`)? If so then it seems to be quite easy but I'm not sure what would be a proper test here - catching `IOException` as a reasult of `failIO`? That looks like an implementation defail of `MonadFail` for `IO` and doesn't seem to be a part of its public contract

**Comment by barrucadu** [comment]
Hmm, I didn't know that `fail` for `IO` used `raiseIO#` under the hood.

In that case, being able to catch it seems like definitely the correct behaviour: but dejafu should probably raise it as an `IOException` rather than the `MonadFailException` type it currently uses, as you can't conveniently write code which would catch a `fail` from both `IO` and `ConcT ...`

**Comment by qrilka** [comment]
I think `MonadFailException` is more correct here as at least theoretically `ConcT` should work for other monad and some of them could have their own instance of `MonadFail`.
So probably this issue should be closed as not actually applicable.

**Comment by barrucadu** [comment]
That's a good point, I agree.
