### ISSUE TITLE
Crosscheck GHC RTS behavior with dejafu

### ISSUE THREAD

**Issue by robinp** [barrucadu/dejafu#163]
Just an idea, due to every recent GHC version finding some RTS bug related to STM:

The idea is to autogen Haskell code, then either

a) Use uniplate to rewrite patterns, assert that behavior before and after is as expected (this is like the Sig example, but in auto-generated contexts)

b) Simulate the result set,  if dejafu doesn't abort then run the code for real, and check that the real results are a subset of the expected set. If it doesn't, then it is either a dejafu bug or an RTS bug.

**Comment by barrucadu** [comment]
So in principle this sounds like a good idea, but I suspect that generating interesting code would be really tricky.
