### ISSUE TITLE
Model IO primitives with MonadConc

### ISSUE THREAD

**Issue by robinp** [barrucadu/dejafu#164]
There's recurring discussion about proper ways of handling exceptions around resource allocation, see for example https://github.com/fpco/safe-exceptions/issues/3.

If a few IO primitives like `hClose` were modeled using `MonadConc`, replicating possible interruption points / blocking / etc, it would be easier to check the properties of suggested error handling mechanisms. 

A test scenario could be written, and `dejafu` would enumerate all the possible outcomes. @Yuras @snoyberg

**Comment by barrucadu** [comment]
Non-concurrency IO is out of scope, as it's hard to support properly.

For example, if `hClose` (and presumably `hOpen`) were in `MonadConc`, then it wouldn't be unreasonable for someone to ask for `handleToFd`, `threadWaitRead`, `threadWaitWrite`, `threadWaitReadSTM`, and `threadWaitWriteSTM`.  But implementing those operations introduces another source of nondeterminism, which significantly complicates everything.  Incidentally, this is why `threadCapability` isn't in `MonadConc`: I suspect it's far more trouble that it's worth.

If just `hOpen` and `hClose` were there, with no other `Handle`-using operations, then there would need to be a way to turn a `MonadConc` `Handle` into an `IO` `Handle`, so operations from outside `MonadConc` could be used.  But that would just lead to `MonadConc` and `IO` code being mixed together, which leads to the undesirable situation of *some* `Handle` code being testable but *other* `Handle` code not.  That's far less clear-cut than the current situation, and could lead to people unintentionally writing poor tests and having more confidence in the correctness of something using `Handle`s than they really should.

---

Having said all that, what's in scope changes over time.  Bound threads were once out of scope, but are a major part of the upcoming 1.0.0.0 release.

**Comment by robinp** [comment]
True. Probably it's easier if people supply mockable implementations in their code, if they want to test for these scenarios. Then they also can introduce failures etc. at will.
