### ISSUE TITLE
Somewhat ambiguous property docs

### ISSUE THREAD

**Issue by qrilka** [barrucadu/dejafu#220]
At http://dejafu.readthedocs.io/en/latest/refinement_testing.html#properties I read
```
refines	=>=	…the left is equivalent to, or strictly refines, the right
```
Is it intended that the description of `refines` uses the same words as the names of other 2 functions i.e. `equivalentTo` and `strictlyRefines`
It looks at least confusing to me.

**Comment by barrucadu** [comment]
It is.  What I tried to express there is that `x =>= y` is the same thing as (`x === y` or `x ->- y`).

**Comment by qrilka** [comment]
Or, that makes sense, probably some phrase like that could be just added to the docs?
