### ISSUE TITLE
What's the story behind removal of `ConcST`?

### ISSUE THREAD

**Issue by abailly** [barrucadu/dejafu#283]
We were using `ConcST` in our tests as this was quite handy to make tested functions pure. We are migrating to LTS-12 and just noticed dejafu 1.0  removed that feature. What was the rationale behind this removal? Any suggestions on a fast track for migrating our code?

**Comment by barrucadu** [comment]
`ConcST` was removed because the implementation of bound threads, which 1.0 introduced, uses `IO`.

If you're not using bound threads (which I guess you're not if you're only just migrating), then you could use `unsafePerformIO` to "recover" purity.

**Comment by abailly** [comment]
And what are the benefits of bound threads? Just curious and want to be enlightened :)

**Comment by barrucadu** [comment]
[Bound threads](http://hackage.haskell.org/package/base-4.11.1.0/docs/Control-Concurrent.html#g:8) are operating system threads, and are necessary if you're using FFI to call a library which uses thread-local state.

**Comment by abailly** [comment]
Apologies if I sound insistent or dumb, but then why is there a need for a FFI call a library depending on TLS? I (think I) know what bound threads are, I am just curious of the design decisions that made you move away from making it possible to use ST...

**Comment by barrucadu** [comment]
I removed `ConcST` because I added `forkOS` to `MonadConc`, and the only reasonable `ST`-based implementation of that would be a runtime error.  Rather than add another type of error, I removed the instance.
