### ISSUE TITLE
tasty-dejafu: How to name tests?

### ISSUE THREAD

**Issue by nomeata** [barrucadu/dejafu#361]
I am surprised that `testAuto` does not take a `TestName`. This way, due to how [`testconc`](https://hackage.haskell.org/package/tasty-dejafu-2.0.0.8/docs/src/Test.Tasty.DejaFu.html#testconc) works, the test group name is always `Deja Fu Tests`, which does not look nice:

```
tests
  Deja Fu Tests
    Never Deadlocks:   OK
    No Exceptions:     OK
    Consistent Result: OK
  Deja Fu Tests
    Never Deadlocks:   OK (2.69s)
    No Exceptions:     OK (2.72s)
    Consistent Result: OK (3.13s)
  Deja Fu Tests
    Never Deadlocks:   OK (0.40s)
    No Exceptions:     OK (0.40s)
    Consistent Result: FAIL (0.80s)
```

I could of course wrap it again in tasty’s `testGroup`, but I’d get another layer of nesting.

I am missing something?

**Comment by nomeata** [comment]
The same applies to `testDejafus`. I could probably work-around by using multiple `testDejafu` test for each subproperty, but then I would lose the benefit of

> This will share work between the predicates, rather than running the concurrent computation many times for each predicate

I assume.

**Comment by barrucadu** [comment]
I'll change those functions to take a `TestName`.

> This will share work between the predicates, rather than running the concurrent computation many times for each predicate

Hmm, that actually hasn't been true for a long time, I'll remove that comment.

**Comment by barrucadu** [comment]
Will #365 work for you?
