### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by barrucadu** [barrucadu/dejafu#4]
An uncaught exception only kills its thread, and exceptions can be thrown to a thread, killing it. Furthermore, actions can be registered which are called when a thread is killed.

In DejaFu, however, an exception during testing would kill everything. This should be fixed, and the missing thread operations should be added to `MonadConc`.

Depends on #3.

(note: read *Tackling the awkward squad: monadic input/output, concurrency, exceptions, and foreign-language calls in Haskell* - SPJ)

**Comment by barrucadu** [comment]
The polymorphism in `catch` makes this really hard because it basically requires being able to inspect the types of things at runtime, which Haskell forbids, for good reason.

**Comment by barrucadu** [comment]
Although `IOError` has associated predicates to determine the type of it. Sadly there is nothing similar for the general case.

**Comment by Taneb** [comment]
Would it be possible to catch SomeException and use Data.Typeable to determine the type of the exception?

An alternative that builds on that is lens' Control.Exception.Lens

**Comment by barrucadu** [comment]
> let tryEvaluate = (\a -> try $ evaluate a) :: a -> IO (Either SomeException a)
    > tryEvaluate (1%0)
    Left Ratio has zero denominator
    > tryEvaluate (1%0) >>= \(Left (SomeException exc)) -> return $ typeOf exc
    ArithException

Awesome, so I can catch `SomeException` and then determine the type. So that's the problem partly solved, now the problem is `catch`. If there are nested `catch`es, I need to call the innermost one whose type matches the exception. I guess a work-around would be to have a new primitive:

    catching :: (Exception e, MonadConc m) => e -> m a -> (e -> m a) -> m a

Because unless the `a` is `Typeable`, I can't use `typeOf` to determine what sort of exception it's catching. Although maybe I could mangle the function to coerce it to `:: (Exception e, MonadConc m) -> m () -> (e -> m ()) -> m ()`, but then that requires the `MonadConc`s to be `Typeable`... which `IO` is not. Hmm.

**Comment by barrucadu** [comment]
Ok, it may be possible to shoe-horn `MonadThrow`+`MonadCatch`+`MonadMask` into this now. Or at least port enough of them into `MonadConc`. Using the existing typeclasses seems like the preferable option.

**Comment by barrucadu** [comment]
Actually I don't need a fancy `catching` function, I can just try to coerce the exception and if a `Nothing` shows up it was the wrong type.
