### ISSUE TITLE
Exceptions?

### ISSUE THREAD

**Issue by pkamenarsky** [barrucadu/dejafu#59]
Just a quick idea: it would be great to being able to test determinism in the presence of exceptions as well - i.e. if an exception is thrown, the tested IO actions should still produce a deterministic result.

I guess the main problem is that different IO actions may throw different exceptions. But otherwise it shouldn't be too hard theoretically, i.e. throw exceptions on subsequent IO actions in different test runs?

**Comment by barrucadu** [comment]
I'm not really sure what you're asking, exception-using code can already be tested. Could you possibly give a small example?
