### ISSUE TITLE
Add tests for named threads, vars, and refs

### ISSUE THREAD

**Issue by barrucadu** [barrucadu/dejafu#98]
`concurrency` gives you the ability to name threads, CRefs, MVars, and TVars.  These names show up in the dejafu traces.

It would be good to have some tests which just create some named things, and check that the set of names in the trace is what it should be.

**Comment by qrilka** [comment]
Hi @barrucadu what do you think about the following:
```
module Integration.Names where

import           Control.Concurrent.Classy hiding (check)
import           Data.Maybe                (mapMaybe)
import           Test.DejaFu.SCT           (runSCT)
import           Test.DejaFu.Types         (Id(..), MVarId(..),
                                            ThreadAction(..))
import           Test.Tasty.HUnit

import           Common

tests :: [TestTree]
tests =
  toTestList
    [ testCase "MVar names" $
      check
        "All traces should use only required MVar names"
        checkMVars
        mvarsAction
    ]
  where
    mvarName1 = "first-mvar"
    mvarName2 = "second-mvar"
    mvarsAction = do
      mvar1 <- newEmptyMVarN mvarName1
      mvar2 <- newEmptyMVarN mvarName2
      _ <- takeMVar mvar1
      _ <- fork $ putMVar mvar1 (1 :: Int)
      _ <- fork $ putMVar mvar2 (2 :: Int)
      _ <- fork $ putMVar mvar1 3
      (,) <$> readMVar mvar1 <*> readMVar mvar2
    checkMVars =
      let validMVid (MVarId (Id (Just n) _)) = n `elem` [mvarName1, mvarName2]
          validMVid _ = False
          maybeMVarId (NewMVar mvid) = Just mvid
          maybeMVarId (BlockedReadMVar mvid) = Just mvid
          maybeMVarId (PutMVar mvid _) = Just mvid
          maybeMVarId (BlockedPutMVar mvid) = Just mvid
          maybeMVarId (TakeMVar mvid _) = Just mvid
          maybeMVarId (BlockedTakeMVar mvid) = Just mvid
          maybeMVarId (ReadMVar mvid) = Just mvid
          maybeMVarId _ = Nothing
      in all validMVid . mapMaybe maybeMVarId
    check msg validActions testAction = do
      outcomes <- runSCT defaultWay defaultMemType testAction
      let extractActions = map $ \(_, _, action) -> action
          actions = [extractActions trace | (_, trace) <- outcomes]
      assertBool msg $ any validActions actions
```
It's about MVars at the moment but should be easily extended with test cases for threads, tvars and refs

**Comment by barrucadu** [comment]
I think instead of pattern matching on the `ThreadAction`, which would break if more `MVar` actions were added, it would be more robust to use `mvarOf . simplifyAction`.  Those functions live in `Test.DejaFu.Internal`, and provide just about what we want:

```
mvarOf . simplifyAction :: ThreadAction -> Maybe MVarId
crefOf . simplifyAction :: ThreadAction -> Maybe CRefId
tvarsOf                 :: ThreadAction -> Set TVarId
```

Then from `Test.DejaFu.Utils` there's `threadNames`, which completes the set.

---

So I think there are two good ways to go about this:

1. use those functions from `Test.DejaFu.Internal` directly; or
2. add new `mvarNames`, `crefNames`, and `tvarNames` functions to `Test.DejaFu.Utils` and use those.

**Comment by qrilka** [comment]
Oh, great, haven't look into that module yet

**Comment by qrilka** [comment]
@barrucadu those functions only return affected entities so e.g. `NewMVar` won't get checked, for threads it makes sense to add `tidsOf :: ThreadAction -> Set ThreadId` and the question is whethere `Fork` should return thread id in this function

**Comment by barrucadu** [comment]
> those functions only return affected entities so e.g. `NewMVar` won't get checked

Hmm, I still don't like the idea of (effectively) duplicating code.  How about:

```haskell
mvar (NewMVar mvid) = Just mvid
mvar a = mvarOf (simplifyAction a)
```

> `tidsOf :: ThreadAction -> Set ThreadId`

When would this return more than one `ThreadId`?

**Comment by qrilka** [comment]
What about MVar or STM actions? Shouldn't ids of all affected threads be returned (and checked)?

**Comment by barrucadu** [comment]
Ah, I see now.  Yes, they should.

**Comment by barrucadu** [comment]
`tvarsOf` doesn't return `TVar`s created, only those which have been read or written.  For consistency, either `tidsOf` should not include forks, or it should and `tvarsOf` should be changed to include created `TVar`s.

I'm leaning towards the latter, as creating a `TVar` *does* write to it.  So: `tvarsWritten` should also have a case for `TNew`; and `tidsOf` should check `Fork` and `ForkOS`, as well as all the actions which include a list of thread IDs.

Then named thing tests will have a minimal amount of code duplication.
